### ISSUE TITLE
Download only old mails

### ISSUE THREAD

**Issue by freetopoi** [coloriz/izms#4]
Hi,

Just wanna check if it's possible to only download the mails that I don't have. My home wifi suddenly dropped and it stops downloading them halfway. Now when I try, it states no new mails.

**Comment by coloriz** [comment]
It's not implemented.

 The problem is due to the order it downloads mails.

https://github.com/coloriz/izone-mail-shelter/blob/e29621091bf6ef42854da8551d95ae884c8e901f/izonemail/izonemail.py#L101

Considering the fact that it's unable to know the last page number (where the oldest mail is) in advance,
I had chosen the easy path – just start downloading from the newest one.

and I'm well aware of its potential issues, like yours.
Maybe it's time for my codes to be revised :)

Anyway to start downloading from somewhere in the middle,
https://github.com/coloriz/izone-mail-shelter/blob/e29621091bf6ef42854da8551d95ae884c8e901f/run.py#L55
I encourage you to change this page number manually.

Each page has 20 mails at most.
So `page` should be `(cnt + 1) // 20 + 1` where `cnt` = the number of mail downloaded so far.
and be sure to change `download_path`.

**Comment by freetopoi** [comment]
Thanks, I tried changing the page number as what you stated, the download starts somewhere around there!

Thank you!
